---

- debug: msg="Version set to {{ icu_version }}"

- name: Make Sure All Required Packages Are Present
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - gcc
    - make

- name: Include version-specific variables for ICU.
  include_vars: "icu-{{ icu_version }}.yml"

- name: Download ICU with Checksum
  get_url:
    url: "{{ icu_url }}"
    dest: "{{ icu_base }}"
    checksum: "{{ icu_checksum }}"
    timeout: 30
  register: get_url_result
  until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
  retries: 5
  when: icu_checksum is defined

- name: Download ICU without Checksum
  get_url:
    url: "{{ icu_url }}"
    dest: "{{ icu_base }}"
    timeout: 30
    force_basic_auth: yes
  register: get_url_result
  until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
  retries: 5
  when: icu_checksum is not defined

- name: Unarchive ICU
  unarchive:
    src: "{{ icu_base }}/{{ icu_archive_file }}"
    dest: "{{ icu_base }}"
    remote_src: yes
    keep_newer: yes

- name: Check Current ICU Version
  shell: /usr/local/bin/icu-config --version
  register: icu_config_version
  ignore_errors: True

- name: Run Configure ICU
  command: >
      chdir={{ icu_base }}/icu/source
      {{ icu_base }}/icu/source/runConfigureICU Linux/gcc
  register: configureResult
  when: icu_config_version != icu_config_version_expected
  ignore_errors: True

- debug: var=configureResult

- name: Gmake Clean
  command: >
      chdir={{ icu_base }}/icu/source
      /usr/bin/gmake clean
  register: cleanResult
  when: icu_config_version != icu_config_version_expected
  ignore_errors: True

- debug: var=cleanResult

- name: Gmake To Make
  command: >
      chdir={{ icu_base }}/icu/source
      /usr/bin/gmake
  register: makeResult
  when: icu_config_version != icu_config_version_expected
  ignore_errors: True

- debug: var=makeResult

- name: Gmake Check
  command: >
      chdir={{ icu_base }}/icu/source
      /usr/bin/gmake check
  register: checkResult
  ignore_errors: yes
  when: icu_config_version != icu_config_version_expected

- debug: var=checkResult

- name: Gmake Install
  command: >
      chdir={{icu_source}}
      /usr/bin/gmake install
  register: installResult
  ignore_errors: yes
  when: icu_config_version != icu_config_version_expected

- debug: var=installResult

- name: Set ICU_HOME if configured.
  template:
    src: icu_home.sh.j2
    dest: /etc/profile.d/icu_home.sh
    mode: 0644
  when: icu_home is defined
