---

- debug: msg="Version set to {{ icu_version }}"

- name: Include version-specific variables for ICU.
  include_vars: "icu-{{ icu_version }}.yml"

- name: Download ICU with Checksum
  get_url:
    url: "{{ icu_url }}"
    dest: "{{ icu_base }}"
    checksum: "{{ icu_checksum }}"
    timeout: 30
  when: icu_checksum is defined

- name: Download ICU without Checksum
  get_url:
    url: "{{ icu_url }}"
    dest: "{{ icu_base }}"
    timeout: 30
  when: icu_checksum is not defined

- name: Unarchive ICU
  unarchive:
    src: "{{ icu_base }}/{{ icu_archive_file }}"
    dest: "{{ icu_base }}"
    remote_src: yes
    keep_newer: yes

- name: Check Current ICU Version
  shell: /usr/local/bin/icu-config --version
  register: icu_config_version
  ignore_errors: True

- name: Run Configure ICU
  command: >
      chdir={{ icu_base }}/icu/source
      {{ icu_base }}/icu/source/runConfigureICU Linux/gcc
  when: icu_config_version != icu_config_version_expected

- name: Gmake Clean
  command: >
      chdir={{ icu_base }}/icu/source
      /usr/bin/gmake clean
  when: icu_config_version != icu_config_version_expected

- name: Gmake To Make
  command: >
      chdir={{ icu_base }}/icu/source
      /usr/bin/gmake
  when: icu_config_version != icu_config_version_expected

- name: Gmake Check
  command: >
      chdir={{ icu_base }}/icu/source
      /usr/bin/gmake check
  ignore_errors: yes
  when: icu_config_version != icu_config_version_expected

- name: Gmake Install
  command: >
      chdir={{icu_source}}
      /usr/bin/gmake install
  when: icu_config_version != icu_config_version_expected

- name: Set ICU_HOME if configured.
  template:
    src: icu_home.sh.j2
    dest: /etc/profile.d/icu_home.sh
    mode: 0644
  when: icu_home is defined
