---

- name: Unarchive ICU
  unarchive: src=http://download.icu-project.org/files/icu4c/52.1/icu4c-52_1-src.tgz dest={{ icu_base }} remote_src=yes

- name: Set ICU_HOME if configured.
  template:
    src: icu_home.sh.j2
    dest: /etc/profile.d/icu_home.sh
    mode: 0644
  when: icu_home
