---

- debug: msg="Version set to {{ icu_version }}"

- name: Include version-specific variables for ICU.
  include_vars: "icu-{{ icu_version }}.yml"

- name: Download ICU with Checksum
  get_url:
    url: "{{ icu_url }}"
    dest: "{{ icu_base }}"
    checksum: "{{ icu_checksum }}"
  when: icu_checksum is defined

- name: Download ICU without Checksum
  get_url:
    url: "{{ icu_url }}"
    dest: "{{ icu_base }}"
  when: icu_checksum is not defined

- name: Unarchive ICU
  unarchive:
    src: "{{ icu_base }}/{{ icu_archive_file }}"
    dest: "{{ icu_base }}"
    remote_src: yes

- name: Set ICU_HOME if configured.
  template:
    src: icu_home.sh.j2
    dest: /etc/profile.d/icu_home.sh
    mode: 0644
  when: icu_home is defined
