---

- name: Download ICU
  get_url:
    url: "{{ item.url }}"
    dest: "{{ icu_base }}"
    checksum: "{{ item.checksum }}"
  when: item.version == icu_version
  with_items: "{{ icu_versions }}"

- name: Unarchive ICU
  unarchive:
    src: "{{ icu_base }}/icu4c-52_1-src.tgz"
    dest: "{{ icu_base }}"
    remote_src: yes

- name: Set ICU_HOME if configured.
  template:
    src: icu_home.sh.j2
    dest: /etc/profile.d/icu_home.sh
    mode: 0644
  when: icu_home
