---

- include: setup-{{ ansible_os_family }}.yml

- name: Include version-specific variables for ICU.
  include_vars: "icu-{{ icu_version }}.yml"
  ignore_errors: True

- name: Check Current ICU Version
  shell: /usr/local/bin/icu-config --version
  register: icu_config_version
  changed_when: False
  ignore_errors: True

- name: Download ICU with Checksum
  get_url:
    url: "{{ icu_url }}"
    dest: "{{ icu_base }}"
    checksum: "{{ icu_checksum }}"
    timeout: 30
  register: icu_get_url_result
  until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
  retries: 5
  when: icu_config_version.stdout != icu_config_version_expected

- name: Unarchive ICU
  unarchive:
    src: "{{ icu_base }}/{{ icu_archive_file }}"
    dest: "{{ icu_base }}"
    remote_src: yes
  register: icu_unarchive_result
  when: icu_config_version.stdout != icu_config_version_expected

- name: Remove Archive File
  file:
    path: "{{ icu_base }}/{{ icu_archive_file }}"
    state: absent

- name: Fix For Early Version Error parse2DigitYear - See Defaults For Why
  lineinfile:
    dest: "{{ icu_base }}/icu/source/test/intltest/dtfmttst.cpp"
    line: "{{ item.line }}"
    regexp: "{{ item.regex }}"
    state: present
    backrefs: yes
  with_items: "{{ icu_2DigitYearFix }}"
  register: icu_date_fix_result
  when: icu_apply_date_fix

- name: Apply Fixes For ansi compatibility
  include: ansi-compatibility.yml

- name: Set ICU_HOME if configured.
  template:
    src: icu_home.sh.j2
    dest: "/etc/profile.d/{{ icu_home_shell_name }}"
    mode: 0644
  when: icu_set_home

- name: Recompile If Necessary
  include: recompileICU.yml
  when: icu_config_version.stdout != icu_config_version_expected or
        icu_get_url_result|changed or
        icu_unarchive_result|changed or
        icu_date_fix_result|changed or
        icu_fix_messagepattern_result|changed or
        icu_fix_fmtable_result|changed or
        icu_fix_msgfmt_include_result|changed or
        icu_fix_msgfmt_class_result|changed or
        icu_fix_msgfmt_cpp_add_result|changed or
        icu_fix_msgfmt_cpp_remove_result|changed or
        icu_recompile
