---

- name: Make Sure All Required Packages Are Present
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - gcc
    - gcc-c++
    - make
    - tar
  register: icu_package_install
  until: icu_package_install.changed or not icu_package_install.changed
  retries: 5
