---
- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 600
  changed_when: False

- name: Make Sure All Required Packages Are Present
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - g++
    - make
  register: icu_package_install
  until: icu_package_install.changed or not icu_package_install.changed
  retries: 5
